### ISSUE TITLE
Consider distribute this project under an open-source license

### ISSUE THREAD

**Issue by ShamrockLee** [fritzone/autocmake#3]
Thank you for this great project!

This project doesn't include a `LICENSE` file or any information about the license it is distributed under, meaning that it is "all rights reserved". That is, no one except you are legally allowed to download and use it.

It's quite easy to add a license -- just follow the GitHub documentation and add a LICENSE file to this repository.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Here's a website created by by GitHub that helps people choose a license:
https://choosealicense.com/

Some licenses I have heard of (from the most permissive to the most copy-left):

*   [BSD0](https://en.wikipedia.org/wiki/BSD_licenses#0-clause_license_(%22BSD_Zero_Clause_License%22)): Permit everyone to use, modify, and redistribute it freely without any limitation.

*   [MIT License](https://en.wikipedia.org/wiki/MIT_License?wprov=sfla1): Permit everyone to use, modify, and redistrimute it freely as long as they give credit to you by mentioning your name (attribution).

*   [GNU LGPL](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License?wprov=sfla1): Permit everyone to use, modify, and redistribute it, but requiring the redistributed program to open source and license under GNU LGPL or GNU GPL.

*   [GNU GPL](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License?wprov=sfla1): Similar to GNU LGPL, but requires programs that uses this project as a library to also open source and license under GNU GPL.

**Comment by fritzone** [comment]
Done, MIT license added
